name: scom_bundle
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          echo "Step: Install dependencies"
          python -m pip install --upgrade pip
          python -m pip install setuptools python-dotenv nuitka
          python -m pip install -r requirements.txt

      - name: Build package
        run: |
          echo "Step: Build package"
          python setup.py build

      - name: Find generated package
        id: find_package
        shell: bash 
        run: |
          echo "Step: Find generated package"
          if [ ! -f SCOM-*.zip ]; then
            echo "Error: Package file not found!"
            exit 1
          fi
          PACKAGE=$(ls SCOM-*.zip)
          echo "package_name=$PACKAGE" >> $GITHUB_ENV
          echo "Found package: $PACKAGE"

      - name: Upload to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.package_name }}
          asset_name: ${{ env.package_name }}
          content_type: application/zip
